name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: simple-ai.io
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pm2 stop simple-ai.io
          cd /var/www/simple-ai.io
          git checkout master
          git pull
          export PATH=$PATH:/root/.nvm/versions/node/v21.5.0/bin/
          npm install
          npm run build
          pm2 start simple-ai.io
