name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  simple-ai-dot-io:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: simple-ai.io
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /var/www/simple-ai.io
          git checkout master
          git pull
          export PATH=$PATH:~/.nvm/versions/node/v18.16.0/bin/
          npm install
          npm run build
          pm2 restart simple-ai.io
